variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_PATH

.before-script-vcpkg-windows: &before-script-vcpkg-windows
  - Push-Location
  - git submodule update --init vcpkg-registry
  - if (-not (Test-Path -Path "$Env:VCPKG_LOCAL_GIT")) { git clone https://git.moduleus.com/common/sw/3rdparty/vcpkg.git $Env:VCPKG_LOCAL_GIT }
  - $baseline=Select-String -Path "vcpkg-configuration.json" -Pattern '"baseline":\s"(.+?)"' | ForEach-Object { $_.Matches.Groups[1].Value }
  - cd "$Env:VCPKG_LOCAL_GIT"
  - git fetch
  - git checkout $baseline
  - Pop-Location
  - $vcpkg_tag = (Get-Content $Env:VCPKG_LOCAL_GIT\scripts\vcpkg-tool-metadata.txt) | Select-String -Pattern '^VCPKG_TOOL_RELEASE_TAG=(.*)'  | %{$_.Matches.Groups[1].value}
  - $url="https://github.com/microsoft/vcpkg-tool/releases/download/$vcpkg_tag/vcpkg.exe"
  - $destination="$Env:VCPKG_CACHE_PATH\vcpkg-$vcpkg_tag.exe"
  - if(-not(Test-Path $destination)){Invoke-WebRequest -Uri $url -OutFile $destination}
  - Copy-Item $destination "$Env:VCPKG_LOCAL_GIT\vcpkg.exe"

.before-script-vcpkg-linux: &before-script-vcpkg-linux
  - git submodule update --init vcpkg-registry
  - if [ ! -d $VCPKG_LOCAL_GIT ]; then git clone https://git.moduleus.com/common/sw/3rdparty/vcpkg.git $VCPKG_LOCAL_GIT || exit 1; fi
  - baseline=$(grep -Po '"baseline":\s"\K[^"]+' vcpkg-configuration.json)
  - cd "$VCPKG_LOCAL_GIT"
  - git fetch
  - git checkout $baseline
  - cd -
  - vcpkg_tag=$(sed -n 's/^VCPKG_TOOL_RELEASE_TAG=\(.*\)/\1/p' < "$VCPKG_LOCAL_GIT/scripts/vcpkg-tool-metadata.txt")
  - destination="$VCPKG_CACHE_PATH/vcpkg-$vcpkg_tag"
  - if [ ! -f "$destination" ]; then wget -O "$destination" "https://github.com/microsoft/vcpkg-tool/releases/download/$vcpkg_tag/vcpkg-glibc" || exit 1; chmod +x "$destination"; fi
  - cp $destination "$VCPKG_LOCAL_GIT/vcpkg" || exit 1

workflow:
  rules:
    - if: $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"

stages:
  - build

build:ubuntu-with-HDF5-static:
  stage: build
  tags:
    - ubuntu
    - build
    - vm2
  before_script:
    - *before-script-vcpkg-linux
    - pwd
  script:
    - CFLAGS='-fsanitize=undefined,address' CXXFLAGS='-fsanitize=undefined,address' cmake -S . -B CI -DCMAKE_C_COMPILER=/usr/bin/clang-17 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-17 -DCMAKE_AR=/usr/bin/llvm-ar-17 -DCMAKE_AS=/usr/bin/llvm-as-17 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-17 -DCMAKE_LINKER_TYPE=LLD -DCMAKE_TOOLCHAIN_FILE="$VCPKG_LOCAL_GIT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_HOST_TRIPLET=x64-linux -DVCPKG_OVERLAY_TRIPLETS=vcpkg-registry/triplets -DWITH_HDF5=ON -DBUILD_TESTING=ON -DWITH_PYTHON:BOOL=ON -DWITH_MATLAB:BOOL=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - rm -Rf CI/CMakeCache.txt CI/CMakeFiles
    - CFLAGS='-fsanitize=undefined,address' CXXFLAGS='-fsanitize=undefined,address' cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang-17 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-17 -DCMAKE_AR=/usr/bin/llvm-ar-17 -DCMAKE_AS=/usr/bin/llvm-as-17 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-17 -DCMAKE_LINKER_TYPE=LLD -DCMAKE_TOOLCHAIN_FILE="$VCPKG_LOCAL_GIT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_HOST_TRIPLET=x64-linux -DVCPKG_OVERLAY_TRIPLETS=vcpkg-registry/triplets -DCMAKE_INSTALL_PREFIX="install" -DBUILD_SHARED_LIBS=OFF -DWITH_HDF5=ON -DBUILD_TESTING=ON -DWITH_PYTHON:BOOL=ON -DWITH_MATLAB:BOOL=ON -DENABLE_PCH:BOOL=OFF -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
    - cmake --install CI --config Release
    - cd CI
    - ctest --output-on-failure -C Release
  artifacts:
    paths:
      - CI/version.txt
      - CI/compile_commands.json
      - CI/vcpkg_installed/x64-linux/include
      - CI/urx/config.h
      - CI/urx/utils/urx/utils/export.h
      - CI/matlab/binding/urx/matlab/export.h
      - CI/python/urx/python/export.h
    expire_in: 1 day

build:ubuntu-with-HDF5-shared:
  stage: build
  tags:
    - ubuntu
    - build
    - vm2
  before_script:
    - *before-script-vcpkg-linux
    - pwd
  script:
    - cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$VCPKG_LOCAL_GIT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic -DVCPKG_HOST_TRIPLET=x64-linux-dynamic -DVCPKG_OVERLAY_TRIPLETS=vcpkg-registry/triplets -DCMAKE_INSTALL_PREFIX="install" -DBUILD_SHARED_LIBS=ON -DWITH_HDF5=ON -DBUILD_TESTING=ON -DWITH_PYTHON:BOOL=ON -DWITH_MATLAB:BOOL=OFF -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
    - cmake --install CI --config Release
    - cd CI
    - ctest --output-on-failure -C Release
