variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"

stages:
  - build
  - doc
  - format
  - test
  - tag
  - install

doc:Doxygen:
  stage: doc
  tags:
    - docker
  image: $CI_REGISTRY/common/ci/dockerci/doxygen:latest
  script:
    - doxygen doc/Doxyfile
    - mv doc/html public
  dependencies:
    - build:ubuntu-with-HDF5-static
  allow_failure: true
  artifacts:
    paths:
      - public
    expire_in: 1 day

doc:PlantUml:
  stage: doc
  tags:
    - docker
  image: $CI_REGISTRY/common/ci/dockerci/hpp2plantuml:latest
  script:
    - mkdir -p doc/plantuml
    - hpp2plantuml -i "uff/*.h" -o doc/plantuml/architecture.puml
    - sed -r -i "/.+\(.*\).*/d" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Acquisition.*\*-- uff.Excitation\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Acquisition.*\*-- uff.Group\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Acquisition.*\*-- uff.Probe\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Acquisition.*\*-- uff.ReceiveSetup\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Acquisition.*\*-- uff.Wave\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*\*-- uff.Transform\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*\*-- uff.Vector.*D\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Element.*\*-- .*\n\n\n//gm" doc/plantuml/architecture.puml
    - perl -0777 -i -pe "s/^.*uff\.Element.*\*-- .*\n\n\n//gm" doc/plantuml/architecture.puml
    - sed -i 's/std:://g' doc/plantuml/architecture.puml
    # - sed -r -i "/\+--\ uff\.GroupData::VecDataType.*/d" doc/plantuml/architecture.puml
    # - perl -0777 -i -pe "s/^.*class\ GroupData::VecDataType.*\n.*}\n\n//gm" doc/plantuml/architecture.puml
    - mkdir -p public/plantuml
    - plantuml doc/plantuml/architecture.puml
    - mv doc/plantuml/architecture.* public/plantuml/
  dependencies:
    - build:ubuntu-with-HDF5-static
  allow_failure: true
  artifacts:
    paths:
      - public
    expire_in: 1 day

format:clang-format:
  stage: format
  tags:
    - ubuntu
    - clang-format
  script:
    - find . -type f -name "*.cpp" -or -name "*.cc" -or -name "*.hpp" -or -name "*.h" |xargs clang-format-14 --style=file --dry-run --Werror
  dependencies: []

format:cmake-format:
  stage: format
  tags:
    - ubuntu
    - cmake-format
  script:
    - find . -name "CMakeLists.txt" | xargs cmake-format -i
    - if [ -n "$(git diff-index --name-only HEAD --)" ]; then echo "Please, format your CMake files."; echo "$(git diff-index --name-only HEAD --)"; exit 1; fi
  dependencies: []

format:clang-tidy:
  stage: format
  tags:
    - ubuntu
    - clang-tidy
  script:
    - cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DHDF5_DIR="$HDF5_DIR_GCC_64_STATIC_RELEASE" -DCatch2_DIR="$Catch2_DIR_GCC_64_STATIC_RELEASE" -DBUILD_SHARED_LIBS=OFF
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
    - cd CI
    - run-clang-tidy || exit 1
  dependencies:
    - build:ubuntu-with-HDF5-static

format:iwyu:
  stage: format
  tags:
    - ubuntu
    - iwyu
  script:
    - iwyu_tool.py -p CI -j $NUM_PARALLEL -- -Xiwyu --no_default_mappings -Xiwyu --mapping_file="$(pwd)/.iwyu-imp" -Xiwyu --no_fwd_decls > CI/iwyu_tool.log
    - fix_includes.py --nosafe_headers < CI/iwyu_tool.log
    - git diff > CI/iwyu.patch
    - cat CI/iwyu.patch
    - if [[ `git status --porcelain` ]]; then echo "Please apply iwyu patch to fix your includes"; exit 1; fi
  dependencies:
    - build:ubuntu-with-HDF5-static
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - CI/iwyu_tool.log
      - CI/iwyu.patch
    expire_in: 1 day

tag:version:
  stage: tag
  dependencies:
    - build:ubuntu-with-HDF5-shared
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git tag $(cat CI/version.txt)
    - git push --tags
  tags:
    - ubuntu
    - build

build:windows-with-HDF5-static:
  stage: build
  tags:
    - win10
    - build
  script:
    - cmake.exe -S . -B CI -G "Visual Studio 17 2022" -A x64 -DHDF5_DIR="$HDF5_DIR_2022_64_STATIC_RELEASE" -DCatch2_DIR="$Catch2_DIR_2022_64_STATIC_RELEASE" -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=OFF -DWITH_HDF5=ON  -DWITH_TEST=ON
    - cmake.exe --build CI --config Release -- /p:CL_MPcount=$NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:windows-with-HDF5-static:
  stage: test
  dependencies:
    - build:windows-with-HDF5-static
  tags:
    - win10
    - test
  script:
    - cd CI
    - ctest --output-on-failure -C Release

install:windows-with-HDF5-static:
  stage: install
  dependencies:
    - build:windows-with-HDF5-static
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - win10
    - build
  script:
    - cmake.exe --install CI --config Release

build:windows-with-HDF5-shared:
  stage: build
  tags:
    - win10
    - build
  script:
    - cmake.exe -S . -B CI -G "Visual Studio 17 2022" -A x64 -DHDF5_DIR="$HDF5_DIR_2022_64_SHARED_RELEASE" -DCatch2_DIR="$Catch2_DIR_2022_64_SHARED_RELEASE" -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=ON -DWITH_HDF5=ON  -DWITH_TEST=ON
    - cmake.exe --build CI --config Release -- /p:CL_MPcount=$NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:windows-with-HDF5-shared:
  stage: test
  dependencies:
    - build:windows-with-HDF5-shared
  tags:
    - win10
    - test
  script:
    - cd CI
    - ctest --output-on-failure -C Release

install:windows-with-HDF5-shared:
  stage: install
  dependencies:
    - build:windows-with-HDF5-shared
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - win10
    - build
  script:
    - cmake.exe --install CI --config Release

build:windows-without-HDF5-static:
  stage: build
  tags:
    - win10
    - build
  script:
    - cmake.exe -S . -B CI -G "Visual Studio 17 2022" -A x64 -DCatch2_DIR="$Catch2_DIR_2022_64_STATIC_RELEASE" -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=OFF -DWITH_HDF5=OFF -DWITH_TEST=ON
    - cmake.exe --build CI --config Release -- /p:CL_MPcount=$NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:windows-without-HDF5-static:
  stage: test
  dependencies:
    - build:windows-without-HDF5-static
  tags:
    - win10
    - test
  script:
    - cd CI
    - ctest --output-on-failure -C Release

build:windows-without-HDF5-shared:
  stage: build
  tags:
    - win10
    - build
  script:
    - cmake.exe -S . -B CI -G "Visual Studio 17 2022" -A x64 -DCatch2_DIR="$Catch2_DIR_2022_64_SHARED_RELEASE" -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=ON -DWITH_HDF5=OFF -DWITH_TEST=ON
    - cmake.exe --build CI --config Release -- /p:CL_MPcount=$NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:windows-without-HDF5-shared:
  stage: test
  dependencies:
    - build:windows-without-HDF5-shared
  tags:
    - win10
    - test
  script:
    - cd CI
    - ctest --output-on-failure -C Release

build:ubuntu-with-HDF5-static:
  stage: build
  tags:
    - ubuntu
    - build
  script:
    - cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DHDF5_DIR="$HDF5_DIR_GCC_64_STATIC_RELEASE" -DCatch2_DIR="$Catch2_DIR_GCC_64_STATIC_RELEASE" -DBUILD_SHARED_LIBS=OFF -DWITH_HDF5=ON -DWITH_TEST=ON
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:ubuntu-with-HDF5-static:
  stage: test
  dependencies:
    - build:ubuntu-with-HDF5-static
  tags:
    - ubuntu
    - build
  script:
    - cd CI
    - ctest --output-on-failure -C Release

install:ubuntu-with-HDF5-static:
  stage: install
  dependencies:
    - build:ubuntu-with-HDF5-static
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - ubuntu
    - build
  script:
    - cmake --install CI --config Release

build:ubuntu-with-HDF5-shared:
  stage: build
  tags:
    - ubuntu
    - build
  script:
    - cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DHDF5_DIR="$HDF5_DIR_GCC_64_SHARED_RELEASE" -DCatch2_DIR="$Catch2_DIR_GCC_64_SHARED_RELEASE" -DBUILD_SHARED_LIBS=ON -DWITH_HDF5=ON -DWITH_TEST=ON
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:ubuntu-with-HDF5-shared:
  stage: test
  dependencies:
    - build:ubuntu-with-HDF5-shared
  tags:
    - ubuntu
    - build
  script:
    - cd CI
    - ctest --output-on-failure -C Release

install:ubuntu-with-HDF5-shared:
  stage: install
  dependencies:
    - build:ubuntu-with-HDF5-shared
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - ubuntu
    - build
  script:
    - cmake --install CI --config Release

build:ubuntu-without-HDF5-static:
  stage: build
  tags:
    - ubuntu
    - build
  script:
    - cmake -S . -B CI -DCatch2_DIR="$Catch2_DIR_GCC_64_STATIC_RELEASE" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=OFF -DWITH_HDF5=OFF -DWITH_TEST=ON
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:ubuntu-without-HDF5-static:
  stage: test
  dependencies:
    - build:ubuntu-without-HDF5-static
  tags:
    - ubuntu
    - build
  script:
    - cd CI
    - ctest --output-on-failure -C Release

build:ubuntu-without-HDF5-shared:
  stage: build
  tags:
    - ubuntu
    - build
  script:
    - cmake -S . -B CI -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DBUILD_SHARED_LIBS=ON -DWITH_HDF5=OFF -DCatch2_DIR="$Catch2_DIR_GCC_64_SHARED_RELEASE" -DWITH_TEST=ON
    - cmake --build CI --config Release --parallel $NUM_PARALLEL
  artifacts:
    paths:
      - CI
    expire_in: 1 day

test:ubuntu-without-HDF5-shared:
  stage: test
  dependencies:
    - build:ubuntu-without-HDF5-shared
  tags:
    - ubuntu
    - build
  script:
    - cd CI
    - ctest --output-on-failure -C Release
